In [8]:
import os
from skimage.io import imread
from skimage.transform import resize
import numpy as np

In [9]:
faces_dir = './Faces'
categories = []
# Getting all of the people that have pictures
for folder in os.listdir(faces_dir):
    categories.append(folder)
    
print(categories)

In [15]:
# Preparing the data
data = []
labels = []
# Iterating through all the folders (each folder is a different celebrity)
for cat_indx, category in enumerate(categories):
    # For each picture of each celebrity, process the image
    for file in os.listdir(os.path.join(faces_dir, category)):
        # Getting the image path
        img_path = os.path.join(faces_dir, category, file)
        # Reading image data
        img = imread(img_path)
        # Resizing the image in order to create a uniform size
        img = resize(img, (160, 160))
        # Appending the pixel matrix, as an array, into the "data" list
        data.append(img.flatten())
        # Appending the index of the category into the "labels" list
        labels.append(cat_indx)

data = np.asarray(data)
labels = np.asarray(data)

[[0.54509804 0.58431373 0.63137255 ... 0.62745098 0.49019608 0.41176471]
 [0.09411765 0.09411765 0.0627451  ... 0.08235294 0.12156863 0.12941176]
 [0.0745098  0.08627451 0.16078431 ... 0.08627451 0.06666667 0.08235294]
 ...
 [0.16470588 0.08235294 0.07058824 ... 0.21568627 0.16470588 0.19215686]
 [0.14509804 0.03921569 0.01176471 ... 0.41568627 0.68627451 0.99215686]
 [0.23921569 0.16862745 0.12941176 ... 0.06666667 0.03921569 0.        ]]
